// spa-child-vue/src/views/Home.vue
<!--
 * @Author: 张天昊
 * @Date: 2020-05-06 16:05:21
 * @LastEditors: 张天昊
 * @LastEditTime: 2020-05-07 16:26:46
 * @Description: 
 -->
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png" />
    <p>接受到基座传来的信息{{ user }}</p>
    <button @click="sendMsg2Base('来着vue子应用的消息')">给基座传消息</button>
  </div>
</template>

<script>
import { mapState } from 'vuex'
import { setSpaState } from '@/utils/spa-store'

export default {
  name: 'Home',
  computed: {
    ...mapState('spa', ['spaState']),
    user() {
      return this.spaState.user
    },
  },
  methods: {
    sendMsg2Base(msg) {
      setSpaState({
        ...this.spaState,
        msg,
      })
    },
  },
}
</script>

// spa-child-react/src/pages/Home.js
/*
 * @Author: 张天昊
 * @Date: 2020-05-06 17:41:56
 * @LastEditors: 张天昊
 * @LastEditTime: 2020-05-07 16:23:15
 * @Description:
 */
import React from 'react'
import { useSelector } from 'react-redux'
import { setSpaState } from '../utils/spa-store'
import logo from '../logo.svg'

export default function () {
  const spaState = useSelector((state) => state.spa.spaState)
  const user = spaState.user
  const sendMsg2Base = (msg) => {
    setSpaState({
      ...spaState,
      msg,
    })
  }
  return (
    <header className='App-header'>
      <img src={logo} className='App-logo' alt='logo' />
      <p style={{ color: '#333' }}>接受到基座传来的信息{user}</p>
      <button onClick={sendMsg2Base.bind(null, '来着react子应用的消息')}>给基座传消息</button>
    </header>
  )
}
